const meau = [
    {
        name:'一级菜单1',
        icon:'el-icon-location',
        path:'/index/menu1',
        child:[
            {
                name:'二级菜单1-1',
                icon:'el-icon-user',
                path:'/index/menu11',
                child:[
                    {
                    name:'三级菜单1-1',
                    icon:'el-icon-user',
                    path:'/index/menu111'
                }
                ]
            },
            {
                name:'二级菜单1-2',
                icon:'el-icon-user-solid',
                path:'/index/menu12'
            }
        ]
    },
    {
        name:'一级菜单2',
        icon:'el-icon-document',
        path:'/index/menu2',
        child:[
            {
                name:'二级菜单2-1',
                icon:'el-icon-star-on',
                path:'/index/menu21'
            },
            {
                name:'二级菜单2-2',
                icon:'el-icon-star-off',
                path:'/index/menu22'
            }
        ]
    },
    {
        name:'一级菜单3',
        icon:'el-icon-setting',
        path:'/index/menu3',
        child:[
            {
                name:'二级菜单3-1',
                icon:'el-icon-s-help',
                path:'/index/menu31'
            },
            {
                name:'二级菜单3-2',
                icon:'el-icon-help',
                path:'/index/menu32'
            }
        ]
    }
]

export default meau;