/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HeadTitle: typeof import('./components/headTitle.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Menu: typeof import('./components/menu.vue')['default']
    Menu1: typeof import('./components/menu1.vue')['default']
    Menu2: typeof import('./components/menu2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
